# Generated by Django 5.0.3 on 2024-03-25 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jeux',
            fields=[
                ('jeux_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=2000)),
                ('release', models.IntegerField()),
                ('cover', models.CharField(max_length=50)),
                ('producer', models.CharField(max_length=30)),
            ],
        ),
    ]
